### ISSUE TITLE
Profile page should be responsive on 450 x 640 pixel screen

### ISSUE THREAD

**Issue by djuanit0x** [Harvesthru-Inc/Harvesthru-Web#22]
#20 

<img width="508" alt="screen" src="https://user-images.githubusercontent.com/38167041/69451897-4cab7200-0d15-11ea-849b-abed6d83db25.png">

**Comment by bryanyuan1** [comment]
Good. I will look into that ASAP.

**Comment by bryanyuan1** [comment]
https://github.com/Harvesthru-Inc/Harvesthru-Web/pull/28
Have made the responsive design. Please check it out!
