### ISSUE TITLE
README Build Instruction Clarifications

### ISSUE THREAD

**Issue by efeichen** [Harvesthru-Inc/Harvesthru-Web#9]
I followed the instruction but had hiccups after step 5, I need to ask y'all for the private key, so this could be noted in the instruction.

Also, I believe inside the client folder also needs a `npm install`, so that should be noted for anyone who wants to contribute to frontend.

**Comment by bryanyuan1** [comment]
Thanks for the feedback.

For the private key, Jaden set up the environment variables so I told him to tell you about it. 

For the `npm install`, yes. Both the root folder `harvesthru-web` and the `client` folder contains a `package.json`, which indicates that they both need `node_modules`. So `npm install` at both directories is needed. 

Could you please add that information to our `README` at step 3?

**Comment by jadenpadua** [comment]
Yeah thanks for that, I will go ahead and add an npm install instruction in client directory
